#!/usr/bin/python
import os, sys
import random
from gtkdisplay import run
from classify import GTKClassifier, gst_init
from classify import TMP_CLASSES as CLASSES
from classify import TMP_HIDDEN_SIZE as HIDDEN_SIZE
TEST_FILE_LENGTH=60
TEST_AUDIO_DIR = ("/home/douglas/maori-language-monitoring/"
                   "data/8k-%ss/test" % TEST_FILE_LENGTH)

def main():
    gst_init()

    if 0:
        d = TEST_AUDIO_DIR
        files = [os.path.join(d, x) for x in os.listdir(d)
                 if x.endswith('.wav') and x[0] in classifier.classes]
    else:
        d = "/home/douglas/maori-language-monitoring/data/8k-full"
        files = [os.path.join(d, x) for x in os.listdir(d)
                 if x.endswith('.wav') and x[0] == 'C']

    classifier = GTKClassifier(mfccs=MFCCS,
                               classes=CLASSES,
                               hsize=HIDDEN_SIZE,
                               sinkname='autoaudiosink')
    random.shuffle(files)
    run(classifier, files)


main()
