#!/usr/bin/python

import os, sys
import random

from classify import Classifier, gst_init
from classify import TMP_CLASSES as CLASSES
from classify import TMP_HIDDEN_SIZE as HIDDEN_SIZE

TEST_FILE_LENGTH=60
TEST_AUDIO_DIR = ("/home/douglas/maori-language-monitoring/"
                   "data/8k-%ss/test" % TEST_FILE_LENGTH)

def test(_dir=TEST_AUDIO_DIR, quiet=False):
    c = Classifier(hsize=HIDDEN_SIZE,
                   channels=1,
                   classes=CLASSES)
    c.quiet = quiet
    files = [os.path.join(_dir, x) for x in os.listdir(_dir) if x.endswith('.wav')
             and x[0] in c.classes]
    random.shuffle(files)

    #files = files[:10]
    score = 0
    misses = []
    results = c.classify_files(*files)
    for winner, scores, votes, fn in results:
        bfn = os.path.basename(fn)
        correct = (winner == bfn[0])
        if correct:
            score += 1
        else:
            misses.append(fn)

    if 0:
        print "MISSES:"
        print '\n'.join('file://' + os.path.join(_dir, x) for x in misses)
        print
    print "%s/%s = %0.2f" % (score, len(files), float(score) / len(files))


def main(argv):
    quiet = False
    if '-q' in argv:
        argv.remove('-q')
        quiet = True
    gst_init()
    test(quiet=quiet)

main(sys.argv[1:])
