#!/usr/bin/python
import os, sys
import random
import argparse
from gtkdisplay import run

from classify import GTKClassifier, gst_init, Gst
from classify_kiwi import WINDOW_SIZE, BASENAME
from classify import Classifier, add_common_args, process_common_args

def main():
    gst_init()
    parser = argparse.ArgumentParser()
    add_common_args(parser, WINDOW_SIZE=WINDOW_SIZE,
                    BASENAME=BASENAME)
    parser.add_argument('-C', '--first-n', type=int, default=0,
                        help="classify this many files")
    parser.add_argument('files', metavar='FILE', nargs='*',
                        help='files to process before --audio-directory')

    args = parser.parse_args()
    c = GTKClassifier(sinkname='autoaudiosink')
    untimed_files = process_common_args(c, args, timed=False)

    files = args.files[:] + [x.fullname for x in untimed_files]
    run(c, files)

main()
