#!/usr/bin/python
import os, sys
import random
from gtkdisplay import run
from classify import GTKClassifier, gst_init
from classify import KIWI_MFCCS as MFCCS
from classify import KIWI_CLASSES as CLASSES
from classify import KIWI_HIDDEN_SIZE as HIDDEN_SIZE
from classify import KIWI_WINDOW_SIZE as WINDOW_SIZE
from classify import KIWI_BASENAME as BASENAME
TEST_AUDIO_DIR = "/home/douglas/corpora/kiwi/test/"

def main(files):
    gst_init()
    classifier = GTKClassifier(mfccs=MFCCS,
                               basename=BASENAME,
                               classes=CLASSES,
                               hsize=HIDDEN_SIZE,
                               window_size=WINDOW_SIZE,
                               sinkname='autoaudiosink')

    if not files:
        d = TEST_AUDIO_DIR
        files = [os.path.join(d, x) for x in os.listdir(d)
                 if x.endswith('.wav') and x[0] in classifier.classes[:-1]]
        random.shuffle(files)

    run(classifier, files)


main(sys.argv[1:])
