#!/usr/bin/python
import os, sys
import argparse

from classify import gst_init, Gst
from classify_kiwi import WINDOW_SIZE, BASENAME
from classify import Classifier, add_common_args, process_common_args

def main():
    gst_init()
    parser = argparse.ArgumentParser()
    add_common_args(parser, WINDOW_SIZE=WINDOW_SIZE,
                    BASENAME=BASENAME)
    group = parser.add_argument_group('kiwi-test specific arguments')
    group.add_argument('-C', '--first-n', type=int, default=0,
                       help="classify this many files")
    group.add_argument('--ground-truth-file',
                       help="write ground truth to this file (CSV)")
    group.add_argument('--classification-file',
                       help="write classifications to this file")
    group.add_argument('--roc', action='store_true',
                       help="show ROC curves")
    group.add_argument('--target-class',
                       help="use this class in reports and ROC")
    group.add_argument('--target-group', type=int, default=0,
                       help="use this class group in reports and ROC")
    group.add_argument('--min-changes', type=int, default=0,
                       help="only test files with at least this many class switches")

    args = parser.parse_args()

    c = Classifier(channels=1)
    timed_files = process_common_args(c, args)
    if args.min_changes:
        timed_files = [x for x in timed_files
                       if len(x.timings) >= args.min_changes]

    if args.first_n:
        timed_files = timed_files[:args.first_n]

    target = None
    if args.target_class:
        target=(args.target_group, args.target_class)

    c.classify(timed_files, ground_truth_file=args.ground_truth_file,
               classification_file=args.classification_file, show_roc=args.roc,
               target_index=target)

main()
